-- Your SQL goes here
CREATE TABLE users(
	id SERIAL PRIMARY KEY NOT NULL,
	username VARCHAR NOT NULL UNIQUE,
	passphrase VARCHAR NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT 'f'
);

CREATE TABLE games(
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE listings(
	id SERIAL PRIMARY KEY NOT NULL,
	user_id INTEGER NOT NULL,
	game_id INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(game_id) REFERENCES games(id)
);